server:
  port: 8080
spring:
  application:
    name: foj
  profiles:
    active: message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foj
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

foj:
  judge-server: 192.168.1.129:5050
  language:
    - C
    - C++
    - Java
  default:
    max-time: 1000
    max-memory: 128
    max-stack: 2
    proc-limit: 50
    file-max: 10240
  jwt:
    key: chzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqz
    effective-time: 30758400000