server:
  port: 8080
spring:
  application:
    name: foj
  profiles:
    active: message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foj
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql #指定分页数据库类型（方言）
  reasonable: true #合理查询超过最大也，则查询最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数，默认false
  params: count=countSql # POJO或者Map中发现了countSql属性，就会作为count参数使用
foj:
  judge-server: 192.168.1.129:5050
  resource-server: 192.168.1.129:80
  language:
    - C
    - C++
    - Java
  default:
    max-time: 10000000000
    max-memory: 104857600
    max-stack: 2
    proc-limit: 50
    file-max: 10240
    avatar-path: D://
    testcase-path: D://testcases
  jwt:
    key: chzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqzchzqz
    effective-time: 30758400000