foj:
  message:
    loginExpired: 登录信息已过期 #登录过期
    notLogin: 用户未登录 #未登录
    permissionDenied: 权限不足 #无权访问
    loginFailed: 用户名或密码错误 #登录失败
    submitFailed: 代码提交失败 #代码提交到judge服务器失败
    argumentError: 请求参数错误 #请求参数错误
    wrongAnswer: 案例未通过 #案例结果错误
    cpuTimeExceeded: 运行超时 # 运行超时
    memoryExceeded: 内存超限 # 内存超限
    emailFormatError: 邮箱格式错误 # 邮箱格式错误
    unqualifiedPassword: 密码应是8-16位字母和数字的组合 # 不合格的密码
    emailExists: 邮箱已占用 # 邮箱已占用
    usernameExists: 用户已存在 # 用户名已存在
    passwordError: 密码错误 # 密码错误
    unsupportedLanguage: 代码语言不受支持 # 不支持的语言
    uploadFailed: 文件上传失败 # 文件上传失败
    dataNotFound: 数据未找到 # 数据未找到